### ISSUE TITLE
Weapon Backend

### ISSUE THREAD

**Issue by Scott-Tatham** [Scott-Tatham/RoyalTumble#14]
- [x]  Create class to control weapon related code. (This class will build weapons from json files.

- [x]  Create weapon base class.

- [x]  Create weapon effect class to store all effects.

- [ ]  Create weapon editor for easy weapon creation/testing. (Gonna be sick as.)
